
spring:
  application:
    name: eureka-server
   
server:
  port: 8082
  
eureka:
  instance:
    hostname: ec2-52-28-53-199.eu-central-1.compute.amazon
    numberRegistrySyncRetries: 0
    preferIpAddress: true
  client:
    region: eu-central-1
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
