spring:
  application:
    name: eureka
   
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka-server-0.0.1-SNAPSHOT/eureka/
    registerWithEureka: false
    fetchRegistry: false
