
spring:
  application:
    name: eureka-server
   
server:
  port: 8082
  
eureka:
  instance:
    hostname: ec2-52-28-53-199.eu-central-1.compute.amazon
  client:
    serviceUrl:
      defaultZone: http://ec2-52-28-53-199.eu-central-1.compute.amazon:8082/eureka/
    registerWithEureka: false
    fetchRegistry: false
