
spring:
  application:
    name: eureka-server
   
server:
  port: 8082
  
eureka:
  region: eu-central-1
  eu-central-1.availabilityZones: eu-central-1a,eu-central-1b,eu-central-1c
  instance:
    hostname: ec2-52-28-53-199.eu-central-1.compute.amazon
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
