
spring:
  application:
    name: eureka-server
   
server:
  port: 8082
  
eureka:
  instance:
    numberRegistrySyncRetries: 0
    preferIpAddress: true
  client:
    region: eu-central-1
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${config_host}:${server.port}/eureka/
