spring:
  application:
    name: gateway

server:
  port: 8080
   
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zull:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
    rating-service:
      path: /rating-service/**
      sensitive-headers: Set-Cookie,Authorization
    eureka:
      path: /eureka/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082

hystrix:
  command:
    book-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    rating-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    eureka:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
