spring:
  application:
    name: gateway

server:
  port: 8080
   
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zull:
  routes:
    patient-service:
      path: /patient-service/**
      sensitive-headers: Set-Cookie,Authorization
    eureka-server:
      path: /eureka/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082

hystrix:
  command:
    patient-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    eureka-server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
