spring:
  application:
    name: gateway

server:
  port: 8080
   
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zull:
  routes:
    eureka-server:
      path: /eureka/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082
    patient-service:
      path: /patient-service/**
      sensitive-headers: Set-Cookie,Authorization
    result-service:
      path: /result-service/**
      sensitive-headers: Set-Cookie,Authorization

hystrix:
  command:
    eureka-server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    patient-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    result-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    
