spring:
  application:
    name: patient-service

server:
  port: 8083
   
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

dynamo:
  region: eu-central-1
  table:
    name: patient

