spring:
  application:
    name: rating-service

server:
  port: 8084

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
