spring:
  application:
    name: result-service

server:
  port: 8084
   
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

dynamo:
  region: eu-central-1
  table:
    name: patient_replica
